### ISSUE TITLE
Error while running GeoNLP

### ISSUE THREAD

**Issue by anirudhalampally** [aibek76/litmus-experiments#1]
when running GeoNLP code in eclipse, it gives an error: "usage: Relation treebank". Could you please help he solve this issue. I am new to Java and not able to find a solution to this on internet. Also mention if I have missed adding any packages.

-Anirudh

**Comment by aibek76** [comment]
I use Maven's pom.xml feature to list all dependencies - see the pom.xml file in the repository for more information. If you figure out how to install and use Maven, then all the dependencies will be automatically downloaded for you.
